#pragma config(Sensor, S4,     infrared,       sensorEV3_IRSensor, modeEV3IR_Remote)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int rotationDegrees = 0;
int irmotor = motorD;
void turnRight(const int amotor, int degrees)
{
	moveMotorTarget(amotor, degrees, 10);
	rotationDegrees += degrees;
	waitUntilMotorStop(amotor);
}

void turnLeft(const int amotor, int degrees)
{
		moveMotorTarget(amotor, -degrees, -10);
		rotationDegrees -= degrees;
		waitUntilMotorStop(amotor);
}

int trackIRDir(int irmotor, int threshold)
{
		int rotationAmount = 20;
		if(rotationDegrees > 180)
		{
			turnLeft(irmotor, 200);
		}
		else if (rotationDegrees < -180)
		{
			turnRight(irmotor, 200);
		}
		if(getIrBeaconDirection(infrared) > threshold)
		{
			turnRight(irmotor, rotationAmount);
		}
		else if (getIrBeaconDirection(infrared) < -threshold)
		{
			turnLeft(irmotor, rotationAmount);
		}
		else
		{
			moveMotorTarget(irmotor, 0, 0);
		}
		return getIRBeaconDirection(infrared);
}

task main()
{
	int taskThreshold = 0;
	while(getIRRemoteButtons(infrared) != 10)
	{
		displayTextLine(0, "Distance: %d", getIRBeaconStrength(infrared));
		displayTextLine(1, "Direction: %d", trackIRDir(irmotor, taskThreshold));
		displayTextLine(2, "Rotation: %d", rotationDegrees);
		displayTextLine(3, "Remote: %d", getIRRemoteButtons(infrared));
	}
	while(rotationDegrees < -taskThreshold)
	{
		turnRight(irmotor, 5);
	}
	while(rotationDegrees > taskThreshold)
	{
		turnLeft(irmotor, 5);
	}
}
