#pragma config(Sensor, S1,     ultrasonic,     sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          trashMotor2,   tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          light,         tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          trashMotor1,   tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int breakCount = 0;
int breakTime = 5000;
int trashsleep = 2000;
int trashRotation = 36000;
char state = 's';
bool distanceBroken(int distance)
{
	if(getUSDistance(ultrasonic) < distance)
		return true;
	return false;
}

void resetMotors(int threshold)
{
	if(getMotorEncoder(trashMotor1) > 0)
	{
		moveMotorTarget(trashMotor1, -getMotorEncoder(trashMotor1), -100);
		moveMotorTarget(trashMotor2, -getMotorEncoder(trashMotor2), -100);
	}
//	if(getMotorEncoder(trashMotor1) < -threshold)
//	{
//		moveMotorTarget(trashMotor1, -getMotorEncoder(trashMotor1), 5);
//		moveMotorTarget(trashMotor2, -getMotorEncoder(trashMotor2), 5);
//	}
//	if(getMotorEncoder(trashMotor1) > threshold)
//	{
//		moveMotorTarget(trashMotor1, -getMotorEncoder(trashMotor1), 5);
//		moveMotorTarget(trashMotor2, -getMotorEncoder(trashMotor2), 5);	}
}

void dumpTrash(int rotationDegrees)
{
	moveMotorTarget(trashMotor1, rotationDegrees, 100);
	moveMotorTarget(trashMotor2, rotationDegrees, 100);
	waitUntilMotorStop(trashMotor2);
	waitUntilMotorStop(trashMotor1);
	sleep(trashsleep);
	resetMotors(0);
}
task turnOnLight()
{
	while(true)
	{
		setMotorSpeed(light, 100);
	}
}

char tracking()
{
	return 's';
}
char dumping()
{
	dumpTrash(trashRotation);
	stopTask(turnOnLight);
	return 't';
}

char takeOutTrash()
{
	startTask(turnOnLight);
	return 't';
}
char still()
{
	if(distanceBroken(20))
	{
		breakCount++;
	}
	else
	{
		breakCount = 0;
	}
	if(breakCount > breakTime)
	{
		playImmediateTone(350, 10);
		breakCount = 0;
		return 'o';
	}
	return 's';
}

task main()
{
		while(true);
		{
		if(state == 's')
		{
			state = still();
		}
		else if (state == 't')
		{
			state = tracking();
		}
		else if (state == 'd')
		{
			state = dumping();
		}
		else if (state == 'o')
		{
			state = takeOutTrash();
		}
		displayTextLine(0, "Distance: %d", getUSDistance(ultrasonic));
		displayTextLine(1, "Counter: %d", breakCount);
		displayTextLine(2, "Encoder: %d", getMotorEncoder(trashMotor1));
		displayTextLine(3, "State: %d", state);
	}
}
